using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Chemistry.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class EnergyReagentCardControl : Control
{
    public string ReagentId { get; }
    public Action<string>? OnPressed;

    public EnergyReagentCardControl(string reagentId, string reagentLabel, Color reagentColor, float powerCost, int amount)
    {
        RobustXamlLoader.Load(this);

        ReagentId = reagentId;
        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor };
        ReagentNameLabel.Text = reagentLabel;

        var totalCost = powerCost * amount;
        FillLabel.Text = Loc.GetString("energy-reagent-dispenser-window-cost", ("cost", MathF.Round(totalCost, 0)));

        MainButton.OnPressed += _ => OnPressed?.Invoke(ReagentId);
    }
}
