using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Orion.Chemistry.UserInterface;

/// <summary>
/// Client-side UI used to control a <see cref="EnergyReagentDispenserComponent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EnergyReagentDispenserWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private float _batteryCharge;
    private float _batteryMaxCharge;
    private float _currentReceiving;

    public event Action<string>? OnDispenseReagentButtonPressed;

    /// <summary>
    /// Create and initialize the dispenser UI client-side. Creates the basic layout,
    /// actual data isn't filled in until the server sends data about the dispenser.
    /// </summary>
    public EnergyReagentDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Update the button grid of reagents which can be dispensed.
    /// </summary>
    /// <param name="inventory">Reagents which can be dispensed by this dispenser</param>
    /// <param name="amount">Amount reagents which can be dispensed</param>
    public void UpdateReagentsList(List<EnergyReagentInventoryItem> inventory, EnergyReagentDispenserDispenseAmount amount)
    {
        if (ReagentList == null)
            return;

        ReagentList.Children.Clear();

        inventory.Sort((x, y) => string.Compare(x.ReagentLabel, y.ReagentLabel, StringComparison.Ordinal));

        var amountValue = (int)amount;
        foreach (var card in inventory
                    .Select(item => new EnergyReagentCardControl( item.ReagentId, item.ReagentLabel, item.ReagentColor, item.PowerCostPerUnit, amountValue )))
        {
            card.OnPressed += reagentId => OnDispenseReagentButtonPressed?.Invoke(reagentId);
            ReagentList.Children.Add(card);
        }
    }

    /// <summary>
    /// Update the UI state when new state data is received from the server.
    /// </summary>
    public void UpdateState(BoundUserInterfaceState message)
    {
        if (message is not EnergyReagentDispenserBoundUserInterfaceState state)
            return;

        _batteryMaxCharge = state.BatteryMaxCharge;
        _batteryCharge = state.BatteryCharge;
        _currentReceiving = state.CurrentReceivingEnergy;

        UpdateContainerInfo(state);
        UpdateReagentsList(state.Inventory, state.SelectedDispenseAmount);
        UpdateBatteryPercent();

        _entityManager.TryGetEntity(state.OutputContainerEntity, out var outputContainerEnt);
        View.SetEntity(outputContainerEnt);

        // Disable the Clear & Eject button if no beaker
        ClearButton.Disabled = state.OutputContainer is null;
        EjectButton.Disabled = state.OutputContainer is null;

        AmountGrid.Selected = ((int)state.SelectedDispenseAmount).ToString();
    }

    private void UpdateBatteryPercent()
    {
        var batteryPercent = _batteryMaxCharge > 0
            ? _batteryCharge / _batteryMaxCharge * 100
            : 0;

        BatteryStatusLabel.Text = Loc.GetString("energy-reagent-dispenser-window-battery-label",
            ("charge", MathF.Round(_batteryCharge, 0)),
            ("max", MathF.Round(_batteryMaxCharge, 0)),
            ("percent", MathF.Round(batteryPercent, 0)));

        BatteryStatusLabel.StyleClasses.Clear();
        BatteryStatusLabel.StyleClasses.Add(batteryPercent switch
        {
            > 60 => "Good",
            > 30 => "Caution",
            _ => "Danger",
        });
    }

    /// <summary>
    /// Update the fill state and list of reagents held by the current reagent container, if applicable.
    /// <para>Also highlights a reagent if it's dispense button is being mouse hovered.</para>
    /// </summary>
    /// <param name="state">State data for the dispenser.</param>
    /// or null if no button is being hovered.
    public void UpdateContainerInfo(EnergyReagentDispenserBoundUserInterfaceState state)
    {
        ContainerInfo.Children.Clear();

        if (state.OutputContainer is null)
        {
            ContainerInfoName.Text = "";
            ContainerInfoFill.Text = "";
            ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
            return;
        }

        // Set Name of the container and its fill status (Ex: 44/100u)
        ContainerInfoName.Text = state.OutputContainer.DisplayName;
        ContainerInfoFill.Text = state.OutputContainer.CurrentVolume + "/" + state.OutputContainer.MaxVolume;

        foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
        {
            // Try get to the prototype for the given reagent. This gives us its name.
            var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

            var nameLabel = new Label { Text = $"{localizedName}: " };
            var quantityLabel = new Label
            {
                Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
            };

            ContainerInfo.Children.Add(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    nameLabel,
                    quantityLabel,
                },
            });
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _batteryCharge = Math.Clamp(_batteryCharge + _currentReceiving * args.DeltaSeconds, 0, _batteryMaxCharge);
        UpdateBatteryPercent();
    }
}
