- type: startingGear
  id: DeathSquadBaseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    suitstorage: OxygenTankFilled   
    eyes: ClothingEyesGlassesDeathsquad
    neck: ExecutiveIDCard
    gloves: ClothingHandsGlovesDeathsquadUnremovable
    outerClothing: ClothingOuterHardsuitDeathsquadUnremovable
    head: ClothingHeadHelmetHardsuitDeathsquad 
    id: DeathsquadPDA
    belt: ClothingBeltDeathsquadWebbing

- type: startingGear
  id: DeathSquadPulseRifleGear
  parent: DeathSquadBaseGear
  equipment:
    shoes: ClothingShoesBootsMagDeathsquad

- type: startingGear
  id: DeathSquadPhoronSabreGear
  parent: DeathSquadBaseGear
  equipment:
    shoes: ClothingShoesBootsMagDeathsquadOn
