- type: startingGear
  id: DeathSquadPulseRifleGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    suitstorage: OxygenTankFilled   
    eyes: ClothingEyesGlassesDeathsquad
    neck: ExecutiveIDCard
    gloves: ClothingHandsGlovesDeathsquadUnremovable
    outerClothing: ClothingOuterHardsuitDeathsquadUnremovable
    head: ClothingHeadHelmetHardsuitDeathsquad 
    shoes: ClothingShoesBootsMagDeathsquad
    id: DeathsquadPDA
    belt: ClothingBeltDeathsquadWebbing

- type: startingGear
  id: DeathSquadPhoronSabreGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    suitstorage: OxygenTankFilled   
    eyes: ClothingEyesGlassesDeathsquad
    neck: ExecutiveIDCard
    gloves: ClothingHandsGlovesDeathsquadUnremovable
    outerClothing: ClothingOuterHardsuitDeathsquadUnremovable
    head: ClothingHeadHelmetHardsuitDeathsquad 
    shoes: ClothingShoesBootsMagDeathsquadOn
    id: DeathsquadPDA
    belt: ClothingBeltDeathsquadWebbing
