// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Administration.Managers;
using Content.Goobstation.Common.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency;
using Content.Goobstation.Shared.ServerCurrency.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Goobstation.Client.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CurrencyWindow : DefaultWindow
    {
        [Dependency] private readonly ICommonCurrencyManager _serverCur = default!;
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IPrototypeManager _protoManager = default!;
        public event Action<ProtoId<TokenListingPrototype>>? OnBuy;
        private bool _isAdmin; // Orion-Edit
        private Dictionary<Button, (DateTime LastClick, TokenListingPrototype Listing)> _buttonClickTimes = new();
        private const double DoubleClickTimeWindow = 1.5; // seconds
        // Orion-Start
        public event Action<ProtoId<TokenListingPrototype>>? OnUse;
        private readonly Dictionary<Button, TokenListingPrototype> _listingByButton = new();
        // Orion-End

        public CurrencyWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            UpdatePlayerBalance();

            _isAdmin = _adminManager.CanCommand("balance:add"); // Orion-Edit

            if (!_isAdmin) // Orion-Edit
                Admin.Visible = false;

            GiftButton.OnPressed += _ => Transfer(GiftPlayer.Text, int.Parse((string)GiftAmmount.Text));

            AdminAddButton.OnPressed += _ => AdminAdd(AdminAddPlayer.Text, int.Parse((string)AdminAddAmmount.Text));

            _serverCur.ClientBalanceChange += UpdatePlayerBalance;

            PopulateTokenButtons();
            UpdateButtonStates();
        }

        // Orion-Start
        public void UpdateInventory(List<TokenInventoryEntry> entries)
        {
            TokenInventoryContainer.DisposeAllChildren();

            if (entries.Count == 0)
            {
                TokenInventoryContainer.AddChild(new Label
                {
                    Text = Loc.GetString("balanceui-inventory-empty"),
                    HorizontalAlignment = HAlignment.Center,
                });
                return;
            }

            foreach (var entry in entries.OrderByDescending(x => x.Amount))
            {
                if (!_protoManager.TryIndex(entry.TokenId, out var listing))
                    continue;

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true,
                };

                row.AddChild(new TextureRect
                {
                    Stretch = TextureRect.StretchMode.KeepCentered,
                    MinSize = new Vector2(24, 24),
                });

                row.AddChild(new Label
                {
                    Text = Loc.GetString("balanceui-inventory-row",
                        ("name", Loc.GetString(listing.Label)),
                        ("amount", entry.Amount)),
                    HorizontalExpand = true,
                });

                var useButton = new Button
                {
                    Text = Loc.GetString("balanceui-inventory-use"),
                };
                useButton.OnPressed += _ => OnUse?.Invoke(entry.TokenId);

                row.AddChild(useButton);
                TokenInventoryContainer.AddChild(row);
                TokenInventoryContainer.AddChild(new Control { MinSize = new Vector2(0, 4) });
            }
        }
        // Orion-End

        private void PopulateTokenButtons()
        {
            TokenListingsContainer.DisposeAllChildren();
            _buttonClickTimes.Clear();
            _listingByButton.Clear(); // Orion

            var tokenListings = _protoManager.EnumeratePrototypes<TokenListingPrototype>()
                .OrderByDescending(x => x.Price);

            foreach (var listing in tokenListings)
            {
                var button = new Button
                {
                    Text = Loc.GetString(listing.Name, ("price", listing.Price)),
                    MinHeight = 40,
                    ToolTip = Loc.GetString(listing.Description)
                };

                button.OnPressed += _ =>
                {
                    if (_buttonClickTimes.TryGetValue(button, out var clickData))
                    {
                        var timeSinceLastClick = (DateTime.Now - clickData.LastClick).TotalSeconds;
                        if (timeSinceLastClick <= DoubleClickTimeWindow)
                        {
                            // Double click occurred
                            OnBuy?.Invoke(listing.ID);
                            ShowConfirmation(Loc.GetString(listing.Label));
                            _buttonClickTimes.Remove(button);
                            button.Text = Loc.GetString(listing.Name, ("price", listing.Price));
                            return;
                        }
                    }

                    // First click
                    _buttonClickTimes[button] = (DateTime.Now, listing);
                    button.Text = Loc.GetString("gs-balanceui-shop-click-confirm");

                    // Reset button text after delay
                    Timer.Spawn(TimeSpan.FromSeconds(DoubleClickTimeWindow),
                        () =>
                    {
                        if (_buttonClickTimes.ContainsKey(button))
                        {
                            button.Text = Loc.GetString(listing.Name, ("price", listing.Price));
                            _buttonClickTimes.Remove(button);
                            UpdateButtonStates();
                        }
                    });
                };

                // Orion-Start
                _listingByButton[button] = listing;

                var listingRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true,
                };

                listingRow.AddChild(new TextureRect
                {
                    Stretch = TextureRect.StretchMode.KeepCentered,
                    MinSize = new Vector2(24, 24),
                });

                listingRow.AddChild(button);
                // Orion-End
                TokenListingsContainer.AddChild(listingRow); // Orion-Edit
                TokenListingsContainer.AddChild(new Control { MinSize = new Vector2(0, 5) });
            }
        }

        private void Transfer(string player, int value)
        {
            if (value == 0) // Orion-Edit
                return;

            _consoleHost.ExecuteCommand("gift " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void AdminAdd(string player, int value)
        {
            if (!_isAdmin || value == 0) // Orion-Edit
                return;

            _consoleHost.ExecuteCommand("balance:add " + player + " " + value);

            UpdatePlayerBalance();
        }

        private void UpdatePlayerBalance() // Goobstation - Goob Coin
        {
            var balance = _serverCur.GetBalance();
            Header.Text = _serverCur.Stringify(balance);
            UpdateButtonStates(balance);
        }

        private void UpdateButtonStates(int? balance = null)
        {
            balance ??= _serverCur.GetBalance(); // Orion-Edit

            Header.Text = _serverCur.Stringify(balance.Value);
            // Orion-Edit-Start
            foreach (var (button, listing) in _listingByButton)
            {
                button.Disabled = balance < listing.Price;
            }
            // Orion-Edit-End
        }

        private void ShowConfirmation(string message)
        {
            ConfirmationMessage.Text = Loc.GetString("gs-balanceui-shop-purchased", ("item", message));
            ConfirmationMessage.Visible = true;
            Timer.Spawn(TimeSpan.FromSeconds(3),
                () =>
            {
                ConfirmationMessage.Visible = false;
                UpdateButtonStates();
            });
        }
    }
}
