using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiBootWindow : FancyWindow
{
    public event Action? InitializationConfirmed;

    private readonly StringBuilder _terminalBuilder = new();
    private readonly List<BootLine> _script = new();
    private StationAiBootBuiState? _state;
    private bool _scriptFinished;
    private int _lineIndex;
    private float _lineTimer;
    private int _typedChars;
    private int _spinnerIndex;

    private static readonly string[] Spinner = ["|", "/", "-", "\\"];

    private const float TypewriterCharsPerSecond = 58f;
    private const float TaskDurationSeconds = 1.2f;

    public StationAiBootWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => InitializationConfirmed?.Invoke();
    }

    public void ApplyState(StationAiBootBuiState state)
    {
        _state = state;
        HeaderLabel.SetMessage(Loc.GetString("station-ai-boot-header", ("name", state.AiName)));
        StatusLabel.SetMessage(Loc.GetString(state.IsMalf
            ? "station-ai-boot-status-malf"
            : "station-ai-boot-status-normal"));

        TerminalPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = state.IsMalf ? Color.FromHex("#180a0a") : Color.FromHex("#0a0f0b")
        };

        ConfirmPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = state.IsMalf ? Color.FromHex("#201010") : Color.FromHex("#101618")
        };

        if (state.Initialized)
        {
            ConfirmButton.Disabled = true;
            ConfirmButton.Text = Loc.GetString("station-ai-boot-complete-button");
            return;
        }

        if (_script.Count == 0)
            BuildScript(state.IsMalf);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state == null || _state.Initialized || _scriptFinished)
            return;

        if (_lineIndex >= _script.Count)
        {
            _scriptFinished = true;
            ConfirmPanel.Visible = true;
            ConfirmButton.Disabled = false;
            return;
        }

        var line = _script[_lineIndex];
        switch (line.Mode)
        {
            case BootLineMode.Instant:
                AppendTerminalLine(Loc.GetString(line.TextKey));
                _lineIndex++;
                _lineTimer = 0f;
                break;
            case BootLineMode.Typewriter:
                UpdateTypewriterLine(line, args.DeltaSeconds);
                break;
            case BootLineMode.Task:
                UpdateTaskLine(line, args.DeltaSeconds);
                break;
        }
    }

    private void UpdateTypewriterLine(BootLine line, float deltaSeconds)
    {
        _lineTimer += deltaSeconds;
        var text = Loc.GetString(line.TextKey);
        var targetChars = (int) (_lineTimer * TypewriterCharsPerSecond);

        if (targetChars <= _typedChars)
            return;

        _typedChars = Math.Min(targetChars, text.Length);
        WriteLastLine($"{text[.._typedChars]}_");

        if (_typedChars < text.Length)
            return;

        WriteLastLine(text);
        _lineIndex++;
        _lineTimer = 0f;
        _typedChars = 0;
    }

    private void UpdateTaskLine(BootLine line, float deltaSeconds)
    {
        _lineTimer += deltaSeconds;
        _spinnerIndex = (_spinnerIndex + 1) % Spinner.Length;

        var prefix = Loc.GetString(line.TextKey);
        if (_lineTimer >= TaskDurationSeconds)
        {
            var suffix = Loc.GetString(line.Success
                ? "station-ai-boot-task-ok"
                : "station-ai-boot-task-fail");
            WriteLastLine($"{prefix} ... {suffix}");
            _lineIndex++;
            _lineTimer = 0f;
            return;
        }

        WriteLastLine($"{prefix} ... {Spinner[_spinnerIndex]}");
    }

    private void BuildScript(bool malf)
    {
        _script.Clear();
        _scriptFinished = false;
        _lineIndex = 0;

        var prefix = malf ? "station-ai-boot-line-malf-" : "station-ai-boot-line-normal-";
        _script.Add(new BootLine(BootLineMode.Instant, $"{prefix}1"));
        _script.Add(new BootLine(BootLineMode.Typewriter, $"{prefix}2"));
        _script.Add(new BootLine(BootLineMode.Task, $"{prefix}3"));
        _script.Add(new BootLine(BootLineMode.Task, $"{prefix}4", Success: !malf));
        _script.Add(new BootLine(BootLineMode.Instant, $"{prefix}5"));
    }

    private void AppendTerminalLine(string text)
    {
        _terminalBuilder.AppendLine(text);
        TerminalLabel.SetMessage(FormattedMessage.FromMarkupPermissive(_terminalBuilder.ToString()));
    }

    private void WriteLastLine(string text)
    {
        var lines = _terminalBuilder.ToString().Split('\n').ToList();

        if (lines.Count == 0 || string.IsNullOrWhiteSpace(lines[^1]))
            lines.Add(text);
        else
            lines[^1] = text;

        _terminalBuilder.Clear();
        for (var i = 0; i < lines.Count; i++)
        {
            if (i == lines.Count - 1 && string.IsNullOrEmpty(lines[i]))
                continue;

            _terminalBuilder.AppendLine(lines[i]);
        }

        TerminalLabel.SetMessage(FormattedMessage.FromMarkupPermissive(_terminalBuilder.ToString()));
    }

    private readonly record struct BootLine(BootLineMode Mode, string TextKey, bool Success = true);

    private enum BootLineMode : byte
    {
        Instant,
        Typewriter,
        Task,
    }
}
